# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket  = "example-tfstate-s3"
    encrypt = false
    key     = "ansible-tower/terraform.tfstate"
    region  = "us-east-1"
  }
}
