---
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:

   - name: Execute initialization of database
     command: psql -h ansible-test.c1zadu1ubwfv.us-east-1.rds.amazonaws.com -a -U qse_svc_user -f db-initial.sql -d postgres
     register: command_output

   - debug:
           var: command_output.stdout_lines