
---
- hosts: nprinting
  gather_facts: no
  tasks:

  - name: Pause for OS
    pause:
      minutes: 5

  - name: Change DNS to DC
    win_dns_client:
      adapter_names: '*'
      ipv4_addresses:
        - 172.31.14.124

  - name: Rename machine
    win_hostname:
      name: "qlick-nprinting"
    register: res

  - name: Reboot if necessary
    win_reboot:
    when: res.reboot_required

  - name: Wait for WinRM to be reachable
    wait_for_connection:
      timeout: 900

  - name: Join to "example.LOCAL"
    win_domain_membership:
      hostname: "example-nprinting"
      dns_domain_name: "example.LOCAL"
      domain_admin_user: "ansible@example.LOCAL"
      domain_admin_password: "Password123"
      state: domain
    register: domain_state

  - name: Wait for 2 minutes
    pause:
      minutes: 2

  - name: reboot if necessary
    win_reboot:
      post_reboot_delay: 120
    when: domain_state.reboot_required

  - name: Adding exampleservice account
    ansible.windows.win_powershell:
      script: |
        function Add-RightToUser([string] $Username, $Right) {
            $tmp = New-TemporaryFile

            $TempConfigFile = "$tmp.inf"
            $TempDbFile = "$tmp.sdb"

            Write-Host "Getting current policy"
            secedit /export /cfg $TempConfigFile

            $sid = ((New-Object System.Security.Principal.NTAccount($Username)).Translate([System.Security.Principal.SecurityIdentifier])).Value

            $currentConfig = Get-Content -Encoding ascii $TempConfigFile

            if ($currentConfig | Select-String -Pattern "^$Right .*$sid.*$") {
                Write-Host "Already has right"
            }
            else {
                Write-Host "Adding $Right to $Username"

                $newConfig = $currentConfig -replace "^$Right .+", "`$0,*$sid"

                Set-Content -Path $TempConfigFile -Encoding ascii -Value $newConfig

                Write-Host "Importing new policy on temp database"
                secedit /import /cfg $TempConfigFile /db $TempDbFile

                Write-Host "Applying new policy to machine"
                secedit /configure /db $TempDbFile /cfg $TempConfigFile

                Write-Host "Updating policy"
                gpupdate /force

                Remove-Item $tmp* -ea 0
            }
        }

        Add-RightToUser -Username 'example.local\exampleservice' -Right 'SeServiceLogonRight'
        Restart-Computer -Force



